# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\ExcelVBA_BAYNA\source\dist\ui\check.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(616, 381)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(616, 381))
        Form.setMaximumSize(QtCore.QSize(616, 381))
        self.lineEdit_sale_30 = QtWidgets.QLineEdit(Form)
        self.lineEdit_sale_30.setGeometry(QtCore.QRect(59, 227, 121, 31))
        font = QtGui.QFont()
        font.setFamily("源ノ角ゴシック JP Heavy")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_sale_30.setFont(font)
        self.lineEdit_sale_30.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(200, 200, 200);")
        self.lineEdit_sale_30.setText("")
        self.lineEdit_sale_30.setFrame(False)
        self.lineEdit_sale_30.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_sale_30.setObjectName("lineEdit_sale_30")
        self.exit_button = QtWidgets.QPushButton(Form)
        self.exit_button.setGeometry(QtCore.QRect(360, 310, 97, 41))
        self.exit_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.exit_button.setText("")
        self.exit_button.setObjectName("exit_button")
        self.start_button = QtWidgets.QPushButton(Form)
        self.start_button.setGeometry(QtCore.QRect(170, 310, 97, 41))
        self.start_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.start_button.setText("")
        self.start_button.setObjectName("start_button")
        self.back_label = QtWidgets.QLabel(Form)
        self.back_label.setGeometry(QtCore.QRect(0, 0, 616, 381))
        self.back_label.setText("")
        self.back_label.setPixmap(QtGui.QPixmap("e:\\ExcelVBA_BAYNA\\source\\dist\\ui\\../image/check.jpg"))
        self.back_label.setObjectName("back_label")
        self.lineEdit_out_5 = QtWidgets.QLineEdit(Form)
        self.lineEdit_out_5.setGeometry(QtCore.QRect(252, 227, 121, 31))
        font = QtGui.QFont()
        font.setFamily("源ノ角ゴシック JP Heavy")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_out_5.setFont(font)
        self.lineEdit_out_5.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(200, 200, 200);")
        self.lineEdit_out_5.setText("")
        self.lineEdit_out_5.setFrame(False)
        self.lineEdit_out_5.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_out_5.setObjectName("lineEdit_out_5")
        self.lineEdit_all = QtWidgets.QLineEdit(Form)
        self.lineEdit_all.setGeometry(QtCore.QRect(439, 227, 121, 31))
        font = QtGui.QFont()
        font.setFamily("源ノ角ゴシック JP Heavy")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_all.setFont(font)
        self.lineEdit_all.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(200, 200, 200);")
        self.lineEdit_all.setText("")
        self.lineEdit_all.setFrame(False)
        self.lineEdit_all.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_all.setObjectName("lineEdit_all")
        self.back_label.raise_()
        self.lineEdit_sale_30.raise_()
        self.exit_button.raise_()
        self.start_button.raise_()
        self.lineEdit_out_5.raise_()
        self.lineEdit_all.raise_()

        self.retranslateUi(Form)
        self.start_button.clicked.connect(Form.start) # type: ignore
        self.exit_button.clicked.connect(Form.exit) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Check Selling"))
