# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\ExcelVBA_BAYNA\source\dist\ui\login.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(601, 328)
        Form.setStyleSheet("background-color: rgb(42, 53, 127);\n"
"color: rgb(255, 255, 255);")
        self.back_label = QtWidgets.QLabel(Form)
        self.back_label.setGeometry(QtCore.QRect(0, 0, 601, 329))
        self.back_label.setText("")
        self.back_label.setObjectName("back_label")
        self.lineEdit_userID = QtWidgets.QLineEdit(Form)
        self.lineEdit_userID.setGeometry(QtCore.QRect(270, 94, 301, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_userID.setFont(font)
        self.lineEdit_userID.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(255, 255, 255);")
        self.lineEdit_userID.setText("")
        self.lineEdit_userID.setFrame(False)
        self.lineEdit_userID.setReadOnly(True)
        self.lineEdit_userID.setObjectName("lineEdit_userID")
        self.lineEdit_password = QtWidgets.QLineEdit(Form)
        self.lineEdit_password.setGeometry(QtCore.QRect(270, 170, 301, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_password.setFont(font)
        self.lineEdit_password.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(255, 255, 255);")
        self.lineEdit_password.setText("")
        self.lineEdit_password.setFrame(False)
        self.lineEdit_password.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit_password.setObjectName("lineEdit_password")
        self.login_button = QtWidgets.QPushButton(Form)
        self.login_button.setGeometry(QtCore.QRect(255, 220, 149, 40))
        self.login_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.login_button.setText("")
        self.login_button.setObjectName("login_button")
        self.logout_button = QtWidgets.QPushButton(Form)
        self.logout_button.setGeometry(QtCore.QRect(430, 220, 149, 40))
        self.logout_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.logout_button.setText("")
        self.logout_button.setObjectName("logout_button")

        self.retranslateUi(Form)
        self.login_button.clicked.connect(Form.login) # type: ignore
        self.logout_button.clicked.connect(Form.logout) # type: ignore
        self.lineEdit_password.textChanged['QString'].connect(Form.text_change) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.lineEdit_userID.setPlaceholderText(_translate("Form", "ユーザーIDを入力してください。"))
        self.lineEdit_password.setPlaceholderText(_translate("Form", "パスワードを入力してください。"))
